services:
  - type: web
    name: weather-dashboard
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WEATHER_API_KEY
        fromService: weather-dashboard
        fromEnvVar: WEATHER_API_KEY 